apiVersion: v1
name: kube-state-metrics
description: kube-state-metrics chart that runs on kubernetes
version: 1.0.0
keywords:
  - kube-state-metrics
  - kubernetes
home: https://github.com/stakater/chart-kube-state-metrics
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
