apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-state-metrics.name" . }}
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
  name: {{ template "kube-state-metrics.name" . }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
  name: {{ template "kube-state-metrics.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-state-metrics.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kube-state-metrics.name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
  name: {{ template "kube-state-metrics.name" . }}-resizer
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  resourceNames: ["{{ template "kube-state-metrics.name" . }}"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
  name: {{ template "kube-state-metrics.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kube-state-metrics.name" . }}-resizer
subjects:
- kind: ServiceAccount
  name: {{ template "kube-state-metrics.name" . }}
