apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    expose: "{{ .Values.kubeStateMetrics.service.expose }}"
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  annotations:
    prometheus.io/scrape: '{{ .Values.kubeStateMetrics.service.scrape }}'
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: {{ .Values.kubeStateMetrics.service.forceSslRedirect }}
      kubernetes.io/ingress.class: {{ .Values.kubeStateMetrics.service.ingressClass }}
      {{- with .Values.kubeStateMetrics.service.annotations }}
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    k8s-app: {{ template "name" . }}
