apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-state-metrics.name" . }}
  labels:
    expose: "{{ .Values.kubeStateMetrics.service.expose }}"
    k8s-app: {{ template "kube-state-metrics.name" . }}
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
{{- if .Values.kubeStateMetrics.service.annotations }}
  annotations:
{{ toYaml .Values.kubeStateMetrics.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    k8s-app: {{ template "kube-state-metrics.name" . }}
